from . import align_uv_test
from . import align_uv_cursor_test
from . import clip_uv_test
from . import copy_paste_uv_test
from . import copy_paste_uv_object_test
from . import copy_paste_uv_uvedit_test
from . import flip_rotate_uv_test
from . import mirror_uv_test
from . import move_uv_test
from . import pack_uv_test
from . import preserve_uv_aspect_test
from . import select_uv_test
from . import smooth_uv_test
from . import texture_lock_test
from . import texture_projection_test
from . import texture_wrap_test
from . import transfer_uv_test
from . import unwrap_constraint_test
from . import uv_bounding_box_test
from . import uv_inspection_test
from . import uv_sculpt_test
from . import uvw_test
from . import world_scale_uv_test
